# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Myframework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Myframework

  pod 'RealmSwift'

  target 'MyframeworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
